# Generated by Django 3.2.7 on 2021-11-23 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password2', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('license', models.ImageField(null=True, upload_to='images/')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password2', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('adhar', models.ImageField(null=True, upload_to='images/')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeekRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leavingfrom', models.CharField(max_length=200)),
                ('leavingto', models.CharField(max_length=200)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.passengerentry')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.ownerentry')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.passengerentry')),
            ],
        ),
        migrations.CreateModel(
            name='Offerride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startlocation', models.CharField(max_length=100)),
                ('endlocation', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.ownerentry')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=100, null=True)),
                ('reply', models.CharField(max_length=100, null=True)),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('rate', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.ownerentry')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.passengerentry')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.seekride')),
            ],
        ),
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=100)),
                ('seat', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('carno', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.ownerentry')),
            ],
        ),
    ]
