# Generated by Django 3.2.7 on 2021-11-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerentry',
            name='password2',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='passengerentry',
            name='password2',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
