# Generated by Django 3.2.7 on 2021-10-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerentry',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passengerentry',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
