# Generated by Django 3.2.7 on 2021-11-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_feedback_owner_feedback_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='carpic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
