# Generated by Django 3.2.7 on 2021-11-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_auto_20211123_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerentry',
            name='password2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='passengerentry',
            name='password2',
            field=models.CharField(max_length=100),
        ),
    ]
