# Generated by Django 3.2.7 on 2021-11-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0003_cardetails_carpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='acnonac',
            field=models.CharField(default='ac', max_length=50),
        ),
    ]
