# Generated by Django 3.2.7 on 2021-11-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0004_cardetails_acnonac'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerride',
            name='amount',
            field=models.CharField(default=100, max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='cardetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carpool.cardetails'),
        ),
        migrations.AddField(
            model_name='offerride',
            name='food',
            field=models.CharField(default='yes', max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='laggage',
            field=models.CharField(default=10, max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='music',
            field=models.CharField(default='yes', max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='pets',
            field=models.CharField(default='yes', max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='smoking',
            field=models.CharField(default='yes', max_length=100),
        ),
    ]
