# Generated by Django 3.2.7 on 2021-11-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0005_auto_20211127_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerride',
            name='carname',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='seatno',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
