# Generated by Django 3.2.7 on 2021-11-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0006_auto_20211128_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerride',
            old_name='carname',
            new_name='carnames',
        ),
    ]
