# Generated by Django 3.2.7 on 2021-11-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0007_rename_carname_offerride_carnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerride',
            name='carnames',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
