# Generated by Django 3.2.7 on 2021-11-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0010_auto_20211128_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerride',
            name='carnames',
            field=models.CharField(default='audi', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerride',
            name='seatno',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
