# Generated by Django 3.2.7 on 2021-11-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0012_auto_20211129_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetails',
            old_name='carpic',
            new_name='image',
        ),
    ]
