# Generated by Django 3.2.7 on 2021-11-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0013_rename_carpic_cardetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekride',
            name='offerride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carpool.offerride'),
        ),
    ]
