# Generated by Django 3.2.7 on 2021-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0014_seekride_offerride'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerride',
            name='status',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
