# Generated by Django 3.2.7 on 2021-12-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0015_offerride_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=1000)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.passengerentry')),
            ],
        ),
    ]
