# Generated by Django 3.2.7 on 2021-12-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0016_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='status',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
