# Generated by Django 3.2.7 on 2021-12-07 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0018_rate_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='0', max_length=500)),
                ('complaint', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.ownerentry')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.passengerentry')),
            ],
        ),
    ]
