# Generated by Django 3.2.7 on 2021-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0019_report_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_passenger',
            name='ownername',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
