# Generated by Django 3.2.7 on 2021-12-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0020_feedback_passenger_ownername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerride',
            name='seatno',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
