# Generated by Django 3.2.7 on 2021-12-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0021_alter_offerride_seatno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerride',
            name='seatno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
