# Generated by Django 3.2.7 on 2021-12-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0022_alter_offerride_seatno'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_passenger',
            name='count',
            field=models.IntegerField(default='0'),
        ),
    ]
