# Generated by Django 3.2.7 on 2021-12-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0023_feedback_passenger_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='status',
            field=models.IntegerField(default='0'),
        ),
    ]
