# Generated by Django 3.2.7 on 2021-12-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0024_alter_rate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_passenger',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
