# Generated by Django 3.2.7 on 2021-12-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0025_alter_feedback_passenger_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_passenger',
            name='count',
        ),
        migrations.AddField(
            model_name='feedback_passenger',
            name='total',
            field=models.IntegerField(default='0'),
        ),
    ]
