# Generated by Django 3.2.7 on 2021-12-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0026_auto_20211208_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_passenger',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carpool.ownerentry'),
        ),
    ]
