# Generated by Django 3.2.7 on 2021-12-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0028_alter_feedback_passenger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_passenger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carpool.usertype'),
        ),
    ]
