# Generated by Django 3.2.7 on 2021-12-09 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0030_offerride_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='owner',
        ),
        migrations.AddField(
            model_name='rate',
            name='offerride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carpool.offerride'),
        ),
    ]
