# Generated by Django 3.2.7 on 2021-12-10 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0031_auto_20211210_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='offerride',
        ),
        migrations.AddField(
            model_name='rate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carpool.ownerentry'),
        ),
    ]
