# Generated by Django 3.2.7 on 2021-12-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0032_auto_20211210_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
