# Generated by Django 3.2.7 on 2021-12-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0033_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekride',
            name='leavingfrom',
        ),
        migrations.RemoveField(
            model_name='seekride',
            name='leavingto',
        ),
    ]
