# Generated by Django 3.2.7 on 2021-12-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0034_auto_20211211_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerride',
            name='food',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerride',
            name='music',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerride',
            name='pets',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerride',
            name='smoking',
            field=models.IntegerField(default='0', max_length=100),
        ),
    ]
