# Generated by Django 3.2.7 on 2021-12-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0035_auto_20211211_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerride',
            name='food2',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='music2',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='pets2',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='offerride',
            name='smoking2',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerride',
            name='food',
            field=models.CharField(default='yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerride',
            name='music',
            field=models.CharField(default='yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerride',
            name='pets',
            field=models.CharField(default='yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='offerride',
            name='smoking',
            field=models.CharField(default='yes', max_length=100),
        ),
    ]
