# Generated by Django 3.2.7 on 2021-12-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0037_alter_offerride_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerride',
            name='food2',
        ),
        migrations.RemoveField(
            model_name='offerride',
            name='music2',
        ),
        migrations.RemoveField(
            model_name='offerride',
            name='pets2',
        ),
        migrations.RemoveField(
            model_name='offerride',
            name='smoking2',
        ),
        migrations.AddField(
            model_name='offerride',
            name='later',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
